### ISSUE TITLE
Swift 2.3 support

### ISSUE THREAD

**Issue by nmccann** [iCodesign/SwiftColor#6]
Hi,

I have a fork which adds 2.3 support, would you consider creating a 2.3 branch so I can create a PR with my changes? Although to be honest the change is a single character, but I thought I'd contribute what I could :)

Thanks,
Noah

**Comment by icodesign** [comment]
Of course, just open a PR. Thanks.

**Comment by nmccann** [comment]
Unfortunately I can't create a PR with a nonexistent destination branch, I could use `master` as the destination, but that would mean that any new users would have to use Swift 2.3 (or use an older release of the project). Are you ok with that?

**Comment by icodesign** [comment]
Sorry for that. Already created the branches now. I don't think we should release it this now, since Xcode 8 is still in beta.

**Comment by nmccann** [comment]
I've created #7, although I have yet to test it with Xcode 8 Beta 6, I doubt it will introduce any changes.

**Comment by icodesign** [comment]
Sorry, I missed that PR. I've added my comments. I'm closing the issue now. Let's move on with that PR.
